version: '3.8'
services:
  postgres-db:
    image: postgres:latest
    networks:
      - app-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  my-app:
    build: .
    ports:
      - "8080:8080"  # Expose the Go app on port 8080
    environment:
      APP_PORT: 8080
      DB_HOST: postgres-db
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_NAME: postgres
      DB_PORT: 5432
      DB_SSLMODE: disable
      DB_TIMEZONE: "America/Sao_Paulo"
    depends_on:
      - postgres-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge